### PR TITLE
Tooltip issue

### PR DESCRIPTION
**Pull request by notsoocool**
## Fixes Issue
#38 Added Tooltip functionality
#25 Fixed pointer Issue

## Screenshots
Screenshot 2024-05-15 at 3 21 37 PM

### CODE REVIEW

**Comment by Nishitbaria** [comment]
> ## Fixes Issue
> #38 Added Tooltip functionality #25 Fixed pointer Issue
> 
> ## Screenshots
> Screenshot 2024-05-15 at 3 21 37 PM

Hey @notsoocool, the feature is working well but it's making ui inconsistent 

see the difference please fix it that:  

After
image

Before
image

**Comment by Nishitbaria** [comment]
Hey @notsoocool 

Still there is miner Difference between both of them you can see : 

After contribution : 

image


Before contribution : 
image

**Please fix the issue I will convert this issue into level3**

**Comment by notsoocool** [comment]
Sure I will update it asap.

**Comment by Nishitbaria** [comment]
Thank you for your contribution @notsoocool

**Pull request merged**
