### PR TITLE
Fixed Incorrect Answer Count Display Issue on Question Page

### PR DESCRIPTION
**Pull request by RashidSiddiqui2004**
Fixes Issue #17 

## Fixes Issue

This PR resolves the issue related to the _incorrect display of answer counts on the question page._ The count of answers now accurately reflects the actual number of answers submitted by users. This enhancement ensures that **_users receive reliable and accurate information_** about the question's engagement level.

## Screenshots

Here, actually there are 8 answers, and the UI also displays 8 answers.

solve6

 
## Note to reviewers
Thank you for assigning this issue to me. It was a great time solving this bug.

### CODE REVIEW

**Comment by Nishitbaria** [comment]
> Fixes Issue #17
> 
> ## Fixes Issue
> This PR resolves the issue related to the _incorrect display of answer counts on the question page._ The count of answers now accurately reflects the actual number of answers submitted by users. This enhancement ensures that **_users receive reliable and accurate information_** about the question's engagement level.
> 
> ## Screenshots
> Here, actually there are 8 answers, and the UI also displays 8 answers.
> 
> solve6
> 
> ## Note to reviewers
> Thank you for assigning this issue to me. It was a great time solving this bug.

please fix the error 


image

**Comment by RashidSiddiqui2004** [comment]
@Nishitbaria resolved the error. 😊

**Comment by Nishitbaria** [comment]
> @Nishitbaria resolved the error. 😊

Hey @RashidSiddiqui2004 Checkout deployment Issue remain same Answer count still show double number 

https://[dev-exchange-apnh8ayer-nishit-barias-projects.vercel.app](https://dev-exchange-apnh8ayer-nishit-barias-projects.vercel.app/)/

**Comment by RashidSiddiqui2004** [comment]
@Nishitbaria Actually, the issue was with the backend, same answer id was stored twice in question document, so, now-on for new questions and answers, the count will be correct.

Also, I assume the existing questions are dummy questions, so it will have have any impact, these can removed in production.

**Comment by Nishitbaria** [comment]
Thank you for your contribution ✨

**Pull request merged**
