### PR TITLE
Add Stop Button for Content Generation just like chatGPT

### LINKED ISSUE #12: [Feature]  Add Pre-Chat Tiles for Direct Input Start, Similar to ChatGPT Interface
### Description

**I would like to add tiles at the beginning of the chat interface, similar to those in ChatGPT, before the chat session starts. These tiles should function such that when a user clicks on one, the chat session begins directly with that input.**

### Screenshots

image

image

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/Dev-Exchange/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by avayyyyyyy**
## Fixes Issue

Closes #12 

## Changes proposed

- Added a stop button for content generation to allow users to cancel the process if needed.

## Note to reviewers

I made the changes without running the project because I don't have the APIs for the .env file. If any issue is encountered jus tell me, and I'll try my best to fix those issues.

### CODE REVIEW

**Comment by Nishitbaria** [comment]
It’s not the issue that you think @avayyyyyyy has. I have created an issue related to adding preTiles  like this not adding stop button 

image

**Comment by avayyyyyyy** [comment]
Do you need tiles like this??? @Nishitbaria 

image

**Comment by Nishitbaria** [comment]
Yes @avayyyyyyy

**Comment by avayyyyyyy** [comment]
Okay got it! @Nishitbaria

**Pull request closed without merging**
