### PR TITLE
feature: added leaderboard feature

### PR DESCRIPTION
**Pull request by Sahilll15**
# Changes Made

## Added Components:

#33 

1. **`app/(root)/leaderboard/page.tsx`:** This file represents a new page component dedicated to displaying the leaderboard. It likely contains logic for fetching and rendering leaderboard data.

2. **`components/shared/LeaderBoardTable.tsx`:** This file introduces a shared component for displaying the leaderboard table. This component is designed to be reusable across different parts of the application and handles the visual presentation of leaderboard data.

## Screenshots

Screenshot 2024-05-16 at 9 49 18 PM

### CODE REVIEW

**Comment by Nishitbaria** [comment]
image

@Sahilll15  please fix this

**Comment by Sahilll15** [comment]
@Nishitbaria done brother

**Comment by Sahilll15** [comment]
@Nishitbaria  wanted to ask like why have you added the next js clerk webhook secret key in the example env like its not working I had to add my own and just caused a lot of confusion overall

**Comment by Sahilll15** [comment]
@Nishitbaria  can you add a label to this actually I forgot to add the issue close id in the PR earlier so it is not getting linked this will be helpfull

**Comment by Nishitbaria** [comment]
Thank you for your contribution @Sahilll15

**Pull request merged**
