### PR TITLE
fix: navbar visibility in mobile view

### PR DESCRIPTION
**Pull request by 01Sriharsha**
- Resolved issue where scrolling wasn't working properly due to which the login button was not visible in the navbar on mobile devices. 
- Implemented necessary style adjustments to ensure proper visibility and functionality of the login button in mobile view.

### CODE REVIEW

**Comment by Nishitbaria** [comment]
> * Resolved issue where scrolling wasn't working properly due to which the login button was not visible in the navbar on mobile devices.
> * Implemented necessary style adjustments to ensure proper visibility and functionality of the login button in mobile view.

can you Link the issue?  and use pr template whenever you are making pr

**Comment by 01Sriharsha** [comment]
> > * Resolved issue where scrolling wasn't working properly due to which the login button was not visible in the navbar on mobile devices.
> > * Implemented necessary style adjustments to ensure proper visibility and functionality of the login button in mobile view.
> 
> can you Link the issue? and use pr template whenever you are making pr

Yes! Got it. Will follow the PR template..

**Comment by 01Sriharsha** [comment]
@Nishitbaria Do I need to create another PR or should I just need to update the current PR's comment with the template

**Comment by Nishitbaria** [comment]
> @Nishitbaria Do I need to create another PR or should I just need to update the current PR's comment with the template

create another pr with pr template

**Pull request closed without merging**
