### PR TITLE
feat: added follow unfollow feature

### LINKED ISSUE #54: [Feature] Add "Follow" and "Unfollow" Feature for Users
## Title
Add "Follow" and "Unfollow" Feature for Users

## Description

**Description:**

Implement a feature that allows users to follow and unfollow other users on the platform. This feature will enable users to stay updated with the activity of developers they are interested in.

**Objectives:**
- Add "Follow" button on user profiles to allow following.
- Add "Unfollow" button on followed user profiles to allow unfollowing.
- Display the list of followed users on the follower's profile page.
- Send notifications or updates to followers when the followed user posts new content or answers questions.
- Ensure the feature is intuitive and seamlessly integrated into the existing UI/UX.

**Requirements:**

1. **Database Changes:**
   - Create a new table to manage follow relationships (e.g., `follows` with columns `follower_id`, `followed_id`, `created_at`).

2. **Backend:**
   - Create API endpoints to handle follow and unfollow actions:
     - `POST /follow` to follow a user.
     - `DELETE /unfollow` to unfollow a user.
   - Ensure proper authentication and authorization checks.
   - Update user profile endpoints to include follower and following counts.

3. **Frontend:**
   - Add "Follow" and "Unfollow" buttons on user profiles.
   - Update the user interface to display followers and following lists.
   - Display follower count and following count on the user's profile page.
   - Show notifications for new content from followed users.

This feature aims to enhance user engagement and interaction within the community, making it easier for developers to connect and collaborate.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/Nishitbaria/Dev-Exchange/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by Sahilll15**
## Fixes Issue

Closes #54

## Changes Proposed

- Added a follow/unfollow button on user profiles.
- Users can view a list of followed and unfollowed users on their profile page.

### Files Updated

- `app/(root)/profile/[id]/page.tsx`
- `components/forms/Profile.tsx`
- `components/shared/Stats.tsx`
- `database/user.model.ts`
- `lib/actions/user.action.ts`

## Screenshots

Screenshot 2024-05-24 at 1 31 38 AM

### CODE REVIEW

**Comment by Sahilll15** [comment]
@Nishitbaria have a look at the PR

**Comment by Nishitbaria** [comment]
Hey @Sahilll15  Please fix the deployment issue : 
image

**Comment by Sahilll15** [comment]
can you just let me know which file is causing the issue?

**Comment by Nishitbaria** [comment]
> can you just let me know which file is causing the issue?

file is not show but you can check locally using `npm run build`

**Comment by Sahilll15** [comment]
> > can you just let me know which file is causing the issue?
> 
> 
> 
> file is not show but you can check locally using `npm run build` 

I did but i cant see any error locally

**Comment by Sahilll15** [comment]
@Nishitbaria  i have solved the error have a look

**Pull request closed without merging**
